twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        cat: '@App\Twig\CatExtension'    
    form_themes: ['form/theme.html.twig']
when@test:
    twig:
        strict_variables: true
